# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Simulating with a Local Projection DGP 
#' @description Simulates a DGP based on the provided information and computes the impulse responses by local projections
#' @param M integer number of simulation replications
#' @param T_ integer sample size
#' @param LP_lags integer number of lags in the LP estimation
#' @param hmax integer maximum horizon
#' @param VAR_coefficients array/cube containing the VAR coefficients, with lags in the slices. These are output by the function make_VAR_coefs 
#' @param Sigma_epsilon covariance matrix of the errors
#' @param irf_1to1 vector vector containing the true impulse responses. These are output by the function irf_from_VAR
#' @param init_partial boolean whether the first step lasso should be only partly penalized
#' @param z_quantiles vector of quantiles from the normal distribution associated with the level of the desired test
#' @param chi2_quantiles vector of quantiles from the chi-squared distribution associated with the level of the desired test
#' @param selection integer in 1:4 which chooses the lambda selection method. 1: BIC, 2: AIC, 3: EBIC, 4: our suggested plug-in selector
#' @param PIconstant constant used in the plug-in estimator
#' @param progress_bar boolean whether a progress bar should be shown
#' @param OLS boolean whether OLS should be used for estimation instead of the desparsified lasso
#' @param threads integer number of cores used in parallel computation
#'@return Returns a list with the following elements: \cr
#'\item{\code{intervals}}{array/cube of confidence intervals of the impulse responses}
#'\item{\code{manual_Thetahat}}{array/cube of the Theta hat matrices}
#'\item{\code{betahats}}{array/cube of beta hats, the first stage lasso estimates}
simulate_LP <- function(M, T_, LP_lags, hmax, VAR_coefficients, Sigma_epsilon, irf_1to1, init_partial, z_quantiles, chi2_quantiles, selection, PIconstant, progress_bar, OLS, threads, seeds_gen, seeds_DL) {
    .Call(`_HDLPrepro_simulate_LP`, M, T_, LP_lags, hmax, VAR_coefficients, Sigma_epsilon, irf_1to1, init_partial, z_quantiles, chi2_quantiles, selection, PIconstant, progress_bar, OLS, threads, seeds_gen, seeds_DL)
}

